// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzBg2pjB8kWjPzhJwIP1QtS-Ro5HKg1uM',
    appId: '1:687692934631:web:c29f3c4ce04f554e8fa142',
    messagingSenderId: '687692934631',
    projectId: 'agenzia-viaggi-definitivo',
    authDomain: 'agenzia-viaggi-definitivo.firebaseapp.com',
    storageBucket: 'agenzia-viaggi-definitivo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRfNPaP0IftZwocYvBPnYPifkU3LLlXzk',
    appId: '1:687692934631:android:22ed883284a560708fa142',
    messagingSenderId: '687692934631',
    projectId: 'agenzia-viaggi-definitivo',
    storageBucket: 'agenzia-viaggi-definitivo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_vBX0GN1df7yRG_szsMTFyuxZm2Ze6g',
    appId: '1:687692934631:ios:c2727ec8900b5ee08fa142',
    messagingSenderId: '687692934631',
    projectId: 'agenzia-viaggi-definitivo',
    storageBucket: 'agenzia-viaggi-definitivo.firebasestorage.app',
    iosBundleId: 'com.example.agenziaViaggiDefinitivo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd_vBX0GN1df7yRG_szsMTFyuxZm2Ze6g',
    appId: '1:687692934631:ios:c2727ec8900b5ee08fa142',
    messagingSenderId: '687692934631',
    projectId: 'agenzia-viaggi-definitivo',
    storageBucket: 'agenzia-viaggi-definitivo.firebasestorage.app',
    iosBundleId: 'com.example.agenziaViaggiDefinitivo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzBg2pjB8kWjPzhJwIP1QtS-Ro5HKg1uM',
    appId: '1:687692934631:web:fdb2811456b4ff408fa142',
    messagingSenderId: '687692934631',
    projectId: 'agenzia-viaggi-definitivo',
    authDomain: 'agenzia-viaggi-definitivo.firebaseapp.com',
    storageBucket: 'agenzia-viaggi-definitivo.firebasestorage.app',
  );
}
